services:
  data-analyst-agent:
    build: .
    container_name: tds-p2
    ports:
      - "7860:7860"
    environment:
      - ENVIRONMENT=production
      - API_HOST=0.0.0.0
      - API_PORT=7860
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./temp:/app/temp
